import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Link from "next/link";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const links = [
    {
        name: 'Cars',
        href: '/cars'
    },
    {
        name: 'Customers',
        href: '/customers'
    },
    {
        name: 'Employees',
        href: '/employees'
    },
    {
        name: 'Sales',
        href: '/sales'
    },
    {
        name: 'Services',
        href: '/services'
    },
]

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>

        <nav className="bg-gray-700 p-4 text-white fixed top-0 left-0 w-full">
            <div className="container mx-auto">
                <h1 className="text-2xl font-semibold">
                    <Link href="/">Autosalon</Link>
                </h1>
                <ul className="mt-2">
                    {links.map((e) => <li key={e.name} className="inline-block mr-4">
                        <Link href={e.href}>{e.name}</Link>
                    </li>)}
                </ul>
            </div>
        </nav>

        <div className="pt-32">
            {children}
        </div>
        </body>
        </html>
    )
}
